Open-Source-Compliance/package-analysis

- analysed-packages/coreutils/version-9.1/README.md
- analysed-packages/coreutils/version-9.1/coreutils-9.1-OSS-disclosure.txt
- analysed-packages/coreutils/version-9.1/coreutils-9.1-SPDX2TV.spdx
Signed-off-by: Caren Kresse [ckresse@osadl.org](mailto:ckresse@osadl.org)
> Adding coreutils v9.1

- analysed-packages/sysvinit-utils/3.04/README.md
- analysed-packages/sysvinit-utils/3.04/sysvinit-3.04-OSS-disclosure.txt
- analysed-packages/sysvinit-utils/3.04/sysvinit-3.04-SPDX2TV.spdx
Signed-off-by: Caren Kresse [ckresse@osadl.org](mailto:ckresse@osadl.org)
> Adding sysvinit-utils v3.04

- .github/workflows/scripts/spdx-tools-java-wrapper.sh
Please have a look at the individual commit messages for the details.
> Verification workflow improvements

- .github/workflows/scripts/convert.sh
- .github/workflows/scripts/spdx-tools-java-wrapper.sh
- .github/workflows/scripts/verify.sh
- .github/workflows/spdx-tools-java.yml
thanks go to Helio Chissini de Castro, who is working on #27
> implement convert functionallity based on #27

- .github/workflows/scripts/convert.sh
- .github/workflows/scripts/spdx-tools-java-wrapper.sh
- .github/workflows/scripts/verify.sh
This also adds rdf to the generated formats.
> Conversion should also generate rdf

- analysed-packages/robin-hood/version-3.11.5/robin-hood-3.11.5.spdx.rdf.xml
- analysed-packages/ruckig/version-0.8.4/ruckig-0.8.4.spdx.rdf.xml
> Created ruckig/version-0.8.4/ruckig-0.8.4.spdx.rdf.xml

- analysed-packages/adduser-debian/version-3.137/README.md
- analysed-packages/adduser-debian/version-3.137/adduser-debian-3.137-OSS-disclosure.txt
- analysed-packages/adduser-debian/version-3.137/adduser-debian-3.137-SPDX2TV.spdx
- analysed-packages/adduser-debian/version-3.137/adduser-debian-3.137.spdx.json
- analysed-packages/adduser-debian/version-3.137/adduser-debian-3.137.spdx.rdf.xml
- analysed-packages/adduser-debian/version-3.137/adduser-debian-3.137.spdx.yaml
Created and added following artifacts from curated adduser-debian-3.137 package:
- README.md
- adduser-debian-3.137-OSS-disclosure.txt
- adduser-debian-3.137-SPDX2TV.spdx
- adduser-debian-3.137.spdx.json
- adduser-debian-3.137.spdx.yaml
- adduser-debian-3.137.spdx.rdf.xml
> Added adduser-debian-3.137 package

- analysed-packages/wireless-regdb/version-2023.02.13/README.md
- analysed-packages/wireless-regdb/version-2023.02.13/wireless-regdb-2023.02.13-OSS-disclosure.txt
- analysed-packages/wireless-regdb/version-2023.02.13/wireless-regdb-2023.02.13-SPDX2TV.spdx
- analysed-packages/wireless-regdb/version-2023.02.13/wireless-regdb-2023.02.13.spdx.json
- analysed-packages/wireless-regdb/version-2023.02.13/wireless-regdb-2023.02.13.spdx.rdf.xml
- analysed-packages/wireless-regdb/version-2023.02.13/wireless-regdb-2023.02.13.spdx.yaml
Dear Mr. Fendt,
Our Fossology server is working properly now. 
Please find all the requested changes in this PR.
You can find the old PR here https://github.com/Open-Source-Compliance/package-analysis/pull/72
> Preparing for wireless-regdb/version-2023.02.13

- analysed-packages/gzip/version-1.12/README.md
Version and qualifiers should be split by a question mark.
> Fix typo in Package URL in README.md

- tools/automatization/Readme.md
- tools/automatization/src/oss/file_operation/file_name_parser.py
- tools/automatization/src/oss/file_operation/files_generator.py
- tools/automatization/src/setup.py
1. Generate document also for windows os with empty space inside folder path
2. Update readme
3. Update the name of the file in ossdisclosure (only of you find the library name and also library version)
4. Make validation configurable
> Apply some fixes

- analysed-packages/jquery-ui-themes/version-1.12.1/README.md
- analysed-packages/jquery-ui-themes/version-1.12.1/jquery-ui-themes-1.12.1-OSS-disclosure.txt
- analysed-packages/jquery-ui-themes/version-1.12.1/jquery-ui-themes-1.12.1-SPDX2TV.spdx
- analysed-packages/jquery-ui-themes/version-1.12.1/jquery-ui-themes-1.12.1.spdx.json
- analysed-packages/jquery-ui-themes/version-1.12.1/jquery-ui-themes-1.12.1.spdx.rdf.xml
- analysed-packages/jquery-ui-themes/version-1.12.1/jquery-ui-themes-1.12.1.spdx.yaml
- analysed-packages/jquery-ui/version-1.12.1/README.md
- analysed-packages/jquery-ui/version-1.12.1/jquery-ui-1.12.1-OSS-disclosure.txt
- analysed-packages/jquery-ui/version-1.12.1/jquery-ui-1.12.1-SPDX2TV.spdx
- analysed-packages/jquery-ui/version-1.12.1/jquery-ui-1.12.1.spdx.json
- analysed-packages/jquery-ui/version-1.12.1/jquery-ui-1.12.1.spdx.rdf.xml
- analysed-packages/jquery-ui/version-1.12.1/jquery-ui-1.12.1.spdx.yaml
Create jquery-ui-themes-1.12.1-OSS-disclosure.txt
Create jquery-ui-themes-1.12.1-SPDX2TV.spdx
Create jquery-ui-themes-1.12.1.spdx.json
Create jquery-ui-themes-1.12.1.spdx.rdf.xml
Create jquery-ui-themes-1.12.1.spdx.yaml
Preparing for jquery-ui/verison-1.12.1/ui
Create jquery-ui-1.12.1-OSS-disclosure.txt
Create jquery-ui-1.12.1-SPDX2TV.spdx
Create jquery-ui-1.12.1.spdx.json
Create jquery-ui-1.12.1.spdx.rdf.xml
Create jquery-ui-1.12.1.spdx.yaml
> Preparing for jquery-ui/verison-1.12.1/themes

- .gitignore
signed-off by: Astrid Spura (aspura@osadl.org)
> Added Apple DS_Store files

- analysed-packages/adodbapi/version-2.6.2.0/README.md
- analysed-packages/adodbapi/version-2.6.2.0/adodbapi-2.6.2.0-OSS-disclosure.txt
- analysed-packages/adodbapi/version-2.6.2.0/adodbapi-2.6.2.0-SPDX2TV.spdx
- version-0.17.4/README.md
- version-0.17.4/altgraph-0.17.4-OSS-disclosure.txt
- version-0.17.4/altgraph-0.17.4-SPDX2TV.spdx
> Add package adodbapi v-2.6.2.0

- analysed-packages/jsonpath-ng/version.1.5.3/README.md
- analysed-packages/jsonpath-ng/version.1.5.3/jsonpath-ng-1.5.3-OSS-disclosure.txt
- analysed-packages/jsonpath-ng/version.1.5.3/jsonpath-ng-1.5.3-SPDX2TV.spdx
> Add package jsonpath-ng/version-1.5.3

- analysed-packages/colorama/version-0.4.6/README.md
- analysed-packages/colorama/version-0.4.6/colorama-0.4.6-OSS-disclosure.txt
- analysed-packages/colorama/version-0.4.6/colorama-0.4.6-SPDX2TV.spdx
> Add package colorama/version-0.4.6

- analysed-packages/idna/version-3.4/README.md
- analysed-packages/idna/version-3.4/idna-3.4-OSS-disclosure.txt
- analysed-packages/idna/version-3.4/idna-3.4-SPDX2TV.spdx
> Add package idna/version-3.4

- analysed-packages/isodate/version-0.6.1/README.md
- analysed-packages/isodate/version-0.6.1/isodate-0.6.1-OSS-disclosure.txt
- analysed-packages/isodate/version-0.6.1/isodate-0.6.1-SPDX2TV.spdx
> Add package isodate/version-0.6.1

- analysed-packages/packaging/version-23.2/README.md
- analysed-packages/packaging/version-23.2/packaging-23.2-OSS-disclosure.txt
- analysed-packages/packaging/version-23.2/packaging-23.2-SPDX2TV.spdx
> Add package packaging/version-23.2

- analysed-packages/attrs/version-23.1.0/README.md
- analysed-packages/attrs/version-23.1.0/attrs-23.1.0-OSS-disclosure.txt
- analysed-packages/attrs/version-23.1.0/attrs-23.1.0-SPDX2TV.spdx
> Add package attrs/version-23.1.0

- analysed-packages/ply/version-3.11/README.md
- analysed-packages/ply/version-3.11/ply-3.11-OSS-disclosure.txt
- analysed-packages/ply/version-3.11/ply-3.11-SPDX2TV.spdx
> Add package ply/version-3.11

- analysed-packages/atlassian-python-api/version-3.41.3/README.md
- analysed-packages/atlassian-python-api/version-3.41.3/atlassian-python-api-3.41.3-OSS-disclosure.txt
- analysed-packages/atlassian-python-api/version-3.41.3/atlassian-python-api-3.41.3-SPDX2TV.spdx
> Add package atlassian-python-api/version-3.41.3

- analysed-packages/charset_normalizer/version-3.3.2/README.md
- analysed-packages/charset_normalizer/version-3.3.2/charset_normalizer-3.3.2-OSS-disclosure.txt
- analysed-packages/charset_normalizer/version-3.3.2/charset_normalizer-3.3.2-SPDX2TV.spdx
> Add package charset_normalizer/version-3.3.2

- tools/create-info-json-files/README.rst
- tools/create-info-json-files/create_info_json.py
- tools/create-info-json-files/info-schema.json
Information of README files in packages will be used to create info.json files
> feat: Script for creation of info.json files

- analysed-packages/debian-archive-keyring/version-debian-2023.3/README.md
- analysed-packages/debian-archive-keyring/version-debian-2023.3/debian-archive-keyring-debian-2023.3-OSS-disclosure.txt
- analysed-packages/debian-archive-keyring/version-debian-2023.3/debian-archive-keyring-debian-2023.3-SPDX2TV.spdx
- analysed-packages/debian-archive-keyring/version-debian-2023.3/debian-archive-keyring-debian-2023.3.json
- analysed-packages/debian-archive-keyring/version-debian-2023.3/debian-archive-keyring-debian-2023.3.rdf.xml
- analysed-packages/debian-archive-keyring/version-debian-2023.3/debian-archive-keyring-debian-2023.3.yaml
Added artifacts for new package debian-archive-keyring-version-2023.3
> Created artifacts for debian-archive-keyring-2023.3

- analysed-packages/debconf/version-debian-1.5.82/README.md
- analysed-packages/debconf/version-debian-1.5.82/debconf-debian-1.5.82-OSS-disclosure.txt
- analysed-packages/debconf/version-debian-1.5.82/debconf-debian-1.5.82-SPDX2TV.spdx
- analysed-packages/debconf/version-debian-1.5.82/debconf-debian-1.5.82.json
- analysed-packages/debconf/version-debian-1.5.82/debconf-debian-1.5.82.rdf.xml
- analysed-packages/debconf/version-debian-1.5.82/debconf-debian-1.5.82.yaml
Created artifacts of newly curated package debconf-debian-1.5.82
> Created debconf-debian-1.5.82

- analysed-packages/keyboard/version-v0.13.5/README.md
Signed-off-by: Astrid Spura (aspura@osadl.org
> Added name of reviewer

- analysed-packages/usrmerge/version-debian-v37/README.md
- analysed-packages/usrmerge/version-debian-v37/usrmerge-debian-v37-OSS-disclosure.txt
- analysed-packages/usrmerge/version-debian-v37/usrmerge-debian-v37-SPDX2TV.spdx
- analysed-packages/usrmerge/version-debian-v37/usrmerge-debian-v37.spdx.json
- analysed-packages/usrmerge/version-debian-v37/usrmerge-debian-v37.spdx.rdf.xml
- analysed-packages/usrmerge/version-debian-v37/usrmerge-debian-v37.spdx.yaml
> Created usrmerge-debian-v37 package
